# ALPACA_API_SECRET_KEYALPACA_API_KEY = ''
# ALPACA_API_SECRET_KEY = ''
# ALPACA_API_BASE_URL = 'https://paper-api.alpaca.markets'
APCA_API_BASE_URL = 'https://paper-api.alpaca.markets'
APCA_API_KEY_ID = 'PK30X482MH0Y5RX80FPR'
APCA_API_SECRET_KEY = 'LJif4LRSDC4BLhu3EprXOvzcaSc5Y9dp3W8Afano'

HEADERS = {'APCA_API_KEY_ID': APCA_API_KEY_ID, 'APCA_API_SECRET_KEY':APCA_API_SECRET_KEY}
